services:
  postgres:
    image: postgres
    container_name: hirelens-postgres
    volumes:
      - ./database-persistence/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hirelens
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: hirelens-redis
    ports:
      - '6379:6379'
